[package]
name = "engine_rocks"
version = "0.0.1"
edition = "2018"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = [
  "encryption/protobuf-codec",
  "engine_traits/protobuf-codec",
  "keys/protobuf-codec",
  "kvproto/protobuf-codec",
  "raft/protobuf-codec",
  "tikv_util/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "encryption/prost-codec",
  "engine_traits/prost-codec",
  "keys/prost-codec",
  "kvproto/prost-codec",
  "raft/prost-codec",
  "tikv_util/prost-codec",
  "txn_types/prost-codec",
]
jemalloc = ["rocksdb/jemalloc"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]
failpoints = ["fail/failpoints"]

[dependencies]
encryption = { path = "../encryption", default-features = false }
engine_traits = { path = "../engine_traits", default-features = false }
file_system = { path = "../file_system" }
keys = { path = "../keys", default-features = false }
num_cpus = "1"
prometheus = { version = "0.10", features = ["nightly"] }
prometheus-static-metric = "0.4"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util", default-features = false }
collections = { path = "../collections", default-features = false }
txn_types = { path = "../txn_types", default-features = false}
lazy_static = "1.4.0"
log_wrappers = { path = "../log_wrappers" }
time = "0.1"
configuration = { path = "../configuration" }
tempfile = "3.0"
serde = "1.0"
serde_derive = "1.0"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
raft = { version = "0.6.0-alpha", default-features = false }
protobuf = "2"
fail = "0.4"

[dependencies.rocksdb]
git = "https://github.com/talenterj/rust-rocksdb.git"
package = "rocksdb"
features = ["encryption", "static_libcpp"]

[dev-dependencies]
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
rand = "0.7"
toml = "0.5"
